### ISSUE TITLE
Exception thrown after running for some time

### ISSUE THREAD

**Issue by derekerdmann** [rit-sse-mycroft/app-speech-to-text#5]
Not entirely sure what caused this, but I consistently run into an exception after the speech-to-text engine is running for a while.

Exception body:

```
System.InvalidOperationException was unhandled by user code
HResult=-2146233079
Message=A task could not complete because the Speech Recognizer engine had timed out.
Source=System.Speech
StackTrace:
   at System.Speech.Recognition.RecognizerBase.RecognizeAsyncStop()
   at System.Speech.Recognition.SpeechRecognitionEngine.RecognizeAsyncStop()
   at SpeechRecognizer.SpeechServer.<DepenedencyHelper>d__54.MoveNext() in 
    c:\Users\Derek\projects\mycroft\app-speech-to-text\SpeechRecognizer\SpeechServer.cs:line 282
```

**Comment by kristenmills** [comment]
How long is "a while"?

**Comment by derekerdmann** [comment]
Maybe 5 minutes? I didn't have the chance to get a good repro, but can try again tomorrow.

**Comment by derekerdmann** [comment]
It may have also been dependent on the microphone being down. I need to investigate it more, then update the bug.

**Comment by kristenmills** [comment]
Alright sounds good.

**Comment by derekerdmann** [comment]
Note from meeting: we may need to destroy and recreate the speech recognition engine regularly, to prevent memory leaks

**Comment by derekerdmann** [comment]
@kristenmills is now working on a fix to terminate the UDP client stream. When the microphone stops pushing data to the socket, we believe the SpeechRecognizerEngine doesn't know that it's not receiving data, so the engine times out when trying to recognize stuff. We'll update when we see how this works.
